## ðŸ¥“ Error Handling :

There are many errors that a user can occour, and we already handle them, but
you can override those methods and handle those errors on your won way.


### Error types
First learn about the errors that can occour.

* `RequiredArgumentNotProvidedError`: This strikes when the required argument is not filled
by the user.
  

* `GotUnexpectedvalueError`: This happens When the user gives more arguments than the command takes.


* `GotMultipleValueError`: When the user specifies both keyword-arg and non-keyword arg on the same parameter then this
error will be raised.

  
* `CommandNotFoundError`: When user calls a command that doesn't exist

  ###
### ðŸš¥ Handling :

### âš  RequiredArgumentNotProvidedError : 

to handle this go to your command class and create a method `OnRequiredArgumentNotProvidedError(self, arg, command_obj)`
* `arg`: the required argument name that was not providede
  

* `command_obj`: your Command object

example: 
```python
class Add(Command):
    
    permissions = [IsAuthenticated]
    
    def process(self):
        val_1 = input("value 1 : ")
        val_2 = input("value 2 : ")
        print(f'\nTotal: {int(val_1) + int(val_2)}')
    
    def OnRequiredArgumentNotProvidedError(self, arg, command_obj):
        print(f"Hey you forgot to fill {arg}")
```

###
### âš  GotUnexpectedvalueError :

to handle this go to your command class and create a method `def OnGotUnexpectedvalueError(self, command_name, value)`
* `command_name`: the command's name that was executed
  

* `value`: the argument value that caused this error

example: 
```python
class Add(Command):
    
    permissions = [IsAuthenticated]
    
    def process(self):
        val_1 = input("value 1 : ")
        val_2 = input("value 2 : ")
        print(f'\nTotal: {int(val_1) + int(val_2)}')
    
    def OnGotUnexpectedvalueError(self, command_name, value):
        """Handles OnGotUnexpectedvalueError"""
        print(f"Hey! Command <{command_name}> got the unexpected value '{value}'")
```


### âš  GotMultipleValueError :
To handle this go to your command class and create a method `OnGotMultipleValueError(self, command_name, arg_name)`
* `command_name`:  the command's name that was executed
  

* `arg_name`: the argument name that got multiple value

example: 
```python
class Add(Command):
    
    permissions = [IsAuthenticated]
    
    def process(self):
        val_1 = input("value 1 : ")
        val_2 = input("value 2 : ")
        print(f'\nTotal: {int(val_1) + int(val_2)}')
    
    def OnGotMultipleValueError(self, command_name, arg_name):
        """Handles OnGotMultipleValueError"""
        print(f"Hey, Command <{command_name}> got multiple values for argument '{arg_name}'")
```


### âš  CommandNotFoundError :
This one is different to implement than the other ones.

create a python file, in my case `error_handlers.py`

```python
from cligo.core.error import CliError


class OnCommandNotFoundError(CliError):

    def on_error(self, command_name):
        print(f"Command '{command_name}' doesn't exist.")
```

The `OnCommandNotFoundError` class must inherit from `cligo.core.error.CliError`
handle it inside `on_error` method. 
* `command_name`: the command's name that was executed

Now you have to set this.

Go to your main file where you have initialized the CliApp
```python
from cligo.cli import CliApp
from error_handler import OnCommandNotFoundError


app = CliApp("AppName")

app.set_on_command_not_found_error(OnCommandNotFoundError)
```
pass the error handler object in app.set_on_command_not_found_error()

That's it You're done. Congrats! ðŸ¥³ðŸŽ‰

###

[<b> Output and more > </b>](8.Output&More.md)

###

[<b> < Permissions </b>](6.Permissions.md)
